version: '2'
services:
  app:
    build:
      context: .
    volumes:
    - ./:/home/webapp/go/src/github.com/monofuel/webapp-template/
    ports:
    - "8085:8085"
  client-build:
    build:
      context: .
    command: make buildClient
    volumes:
    - ./:/home/webapp/go/src/github.com/monofuel/webapp-template/